### ISSUE TITLE
resource id not provided

### ISSUE THREAD

**Issue by aromanocohen** [AndrewKeig/passport-azure-oauth2#1]
Hi Andrew, 

I just want to allow my users to access my WebApp using their Office 365 account in the same way that I allready did with Twitter, Facebook and google.
I have allready created a WebApp in Azure AD.

My app is configured like this:

![image](https://cloud.githubusercontent.com/assets/3505108/16438981/cb8df72e-3d79-11e6-9819-a864e42055ee.png)

And this:

![image](https://cloud.githubusercontent.com/assets/3505108/16438988/dfc730f2-3d79-11e6-9274-e2094183f742.png)

And this:

![image](https://cloud.githubusercontent.com/assets/3505108/16438995/f657630a-3d79-11e6-8538-ba2f18808348.png)

The only permision that I ask for is:

`Read all users' basic profiles`

![image](https://cloud.githubusercontent.com/assets/3505108/16439007/0f2484ee-3d7a-11e6-8a76-8114846fc747.png)

I'am creating my strategy with this values:

```
    microsoftAuth: {
        clientID: '8c4ce02f-f5dc-4fd0-b0a0-49294ad25d53',
        clientSecret: 'ygLgxaGRwNXxtyjdq8Jqs80V+isJVNx7c4gUltUFY10=',
        callbackURL: 'https://nudniq.com/auth/microsoft/callback'
    }
```

But I receive the following error:

```
TokenError: AADSTS50001: Resource identifier is not provided. 
Trace ID: 95f88f5a-95b9-4d3a-86fe-19ae0bbfcc76 
Correlation ID: b056150c-debd-469d-963b-ea362ca93884 
Timestamp: 2016-06-29 01:38:39Z
   at AzureOAuth2.OAuth2Strategy.parseErrorResponse (/home/ec2-user/test2/fastpass/node_modules/passport-oauth2/lib/strategy.js:298:12)
   at AzureOAuth2.OAuth2Strategy._createOAuthError (/home/ec2-user/test2/fastpass/node_modules/passport-oauth2/lib/strategy.js:345:16)
   at /home/ec2-user/test2/fastpass/node_modules/passport-oauth2/lib/strategy.js:171:43
   at /home/ec2-user/test2/fastpass/node_modules/oauth/lib/oauth2.js:177:18
   at passBackControl (/home/ec2-user/test2/fastpass/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/home/ec2-user/test2/fastpass/node_modules/oauth/lib/oauth2.js:143:7)
   at IncomingMessage.emit (events.js:129:20)
   at _stream_readable.js:908:16
   at process._tickDomainCallback (node.js:381:11)
```

Please help me, I dont know what am I doing wrong.

Thank you very much,

Abraham

**Comment by kandaraj** [comment]
As stated in document, pass the `resource: config.resource`

```
this.passport.use("provider", new AzureOAuth2Strategy({
      clientID: config.clientID,
      clientSecret: config.clientSecret,
      callbackURL: config.callbackUri,
      resource: config.resource,
      tenant: config.tenant,
      prompt: 'login',
      state: false
    },
```

**Comment by cnayan** [comment]
Where do we find the resource identifier in Azure AD?
